pipeline {
    agent any

    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }

    stages {
        stage("Fetch code"){
            steps{
                git branch: 'atom', url:'https://github.com/hkhcoder/vprofile-project.git'
            }
        }
        
        stage("Build") {
            steps{
                sh "mvn install -DskipTests"
            }
            post {
                success {
                    echo "Archive the build artifacts"
                    archiveArtifacts artifacts: '**/target/*.war'
                    sh 'ls'
                }
            }
        }

        stage("Unit Test"){
            steps{
                sh "mvn test"
            }
        }

        stage("Checkstyle Analysis"){
            steps{
                sh "mvn checkstyle:checkstyle"
                //Checkstyle is a plugin that performs code analysis to ensure that the code adheres to a specified coding standard. It helps identify and fix code style issues, improving code readability and maintainability.
            }
        }

        stage("Sonar Code analysis") {
            environment{
                scannerHome = tool 'sonar6.2'
                //name saved under Tools section in Jenkins global configuration, which points to the SonarQube Scanner installation directory.
            }
            steps {
                sh 'ls -R src'
              withSonarQubeEnv('sonarserver') {
                sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                //this is a multi-line string (enclosed in triple quotes) that contains the command to run the SonarQube Scanner CLI with various parameters. The parameters specify the project key, project name, project version, source code location, binary files location, test reports location, code coverage reports location, and Checkstyle report location.
                //-D signifies that the following text is a system property that will be passed to the SonarQube Scanner. These properties are used to configure the analysis and provide necessary information about the project being analyzed.
              }
            }
          }


    }
}